import { DataTypes } from "sequelize";

export default (sequelize) => {
  const ChatHistory = sequelize.define(
    "ChatHistory",
    {
      id: {
        type: DataTypes.BIGINT,
        primaryKey: true,
        autoIncrement: true,
      },
      deviceId: {
        type: DataTypes.BIGINT,
        allowNull: false,
        comment: "Device ID this message belongs to",
      },
      sessionId: {
        type: DataTypes.STRING,
        allowNull: false,
        comment: "WhatsApp session ID",
      },
      chatId: {
        type: DataTypes.STRING,
        allowNull: false,
        comment: "WhatsApp chat ID (phone@s.whatsapp.net)",
      },
      phoneNumber: {
        type: DataTypes.STRING,
        allowNull: false,
        comment: "Phone number (without @s.whatsapp.net)",
      },
      messageId: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: "WhatsApp message ID for deduplication",
      },
      direction: {
        type: DataTypes.ENUM("incoming", "outgoing"),
        allowNull: false,
        comment: "Message direction",
      },
      messageType: {
        type: DataTypes.STRING,
        allowNull: false,
        defaultValue: "text",
        comment: "Message type: text, image, video, audio, document, sticker",
      },
      content: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: "Text content of the message",
      },
      mediaUrl: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: "URL for media files (if applicable)",
      },
      caption: {
        type: DataTypes.TEXT,
        allowNull: true,
        comment: "Caption for media messages",
      },
      timestamp: {
        type: DataTypes.DATE,
        allowNull: false,
        defaultValue: DataTypes.NOW,
        comment: "Message timestamp",
      },
      fromMe: {
        type: DataTypes.BOOLEAN,
        allowNull: false,
        defaultValue: false,
        comment: "Whether message was sent by this device",
      },
      senderName: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: "Push name of the sender",
      },
      rawMessage: {
        type: DataTypes.JSON,
        allowNull: true,
        comment: "Raw Baileys message object for debugging",
      },
      // Agent Attribution
      agentId: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: "Agent who sent this message (null for customer or AI)",
      },
      agentName: {
        type: DataTypes.STRING,
        allowNull: true,
        comment: "Agent display name",
      },
      isAiGenerated: {
        type: DataTypes.BOOLEAN,
        defaultValue: false,
        comment: "True if message was generated by AI",
      },
      status: {
        type: DataTypes.ENUM("pending", "sent", "delivered", "read", "failed"),
        defaultValue: "pending",
        allowNull: false,
        comment: "Message delivery status",
      },
      sentAt: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "Timestamp when message was sent to WhatsApp",
      },
      deliveredAt: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "Timestamp when message was delivered",
      },
      readAt: {
        type: DataTypes.DATE,
        allowNull: true,
        comment: "Timestamp when message was read",
      },
    },
    {
      indexes: [
        {
          fields: ["deviceId", "chatId"],
          name: "idx_device_chat",
        },
        {
          fields: ["sessionId", "chatId"],
          name: "idx_session_chat",
        },
        {
          unique: true,
          fields: ["deviceId", "messageId"],
          name: "unique_device_message",
        },
        {
          fields: ["timestamp"],
        },
        {
          fields: ["phoneNumber"],
        },
      ],
      timestamps: true,
    }
  );

  return ChatHistory;
};
